-- The whole schema as of SQLite migration 0044, for a server on PostgreSQL.
--
-- A PostgreSQL server starts here rather than replaying the SQLite history,
-- which is full of table rebuilds that exist only because SQLite cannot alter
-- a column. Every SQLite migration after 0044 needs a PostgreSQL counterpart
-- in this directory; the schema parity test fails until it has one.
--
-- Differences from the SQLite schema, all of them deliberate:
--   INTEGER is BIGINT: several columns hold millisecond timestamps.
--   event_log.seq is an identity column rather than AUTOINCREMENT.
--   Single-row tables default their id to 1, as SQLite's rowid alias did.
--   GLOB checks are the equivalent regular expressions.
--   The rows SQLite migrations seed (built-in roles, settings) are inserted
--   here as they are there.
--   Every table has a rowid identity column: queries order by SQLite's rowid
--   to keep insertion order, and the driver leaves it out of what they return.


CREATE TABLE event_log (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic TEXT NOT NULL,
  type TEXT NOT NULL,
  payload TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE users (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  password_hash TEXT,
  role TEXT NOT NULL DEFAULT 'member',
  created_at TEXT NOT NULL
, suspended_at TEXT, avatar_mode TEXT NOT NULL DEFAULT 'bloop'
  CHECK (avatar_mode IN ('bloop', 'blobatar', 'name')));

CREATE TABLE sessions (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  token TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);

CREATE TABLE agents (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  owner_user_id TEXT NOT NULL REFERENCES users(id),
  name TEXT NOT NULL,
  personality TEXT NOT NULL DEFAULT '',
  model_policy TEXT NOT NULL,
  permissions TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
, availability TEXT NOT NULL DEFAULT 'auto'
  CHECK (availability IN ('auto', 'dnd')), avatar_mode TEXT NOT NULL DEFAULT 'bloop'
  CHECK (avatar_mode IN ('bloop', 'blobatar', 'name')), routing_mode TEXT NOT NULL DEFAULT 'mention_only'
  CHECK (routing_mode IN ('always', 'mention_only', 'relevant', 'disabled')));

CREATE TABLE channel_categories (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  position BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE TABLE conversations (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('dm', 'group', 'channel')),
  name TEXT,
  topic TEXT,
  visibility TEXT CHECK (visibility IN ('public', 'private')),
  post_role TEXT CHECK (post_role IN ('member', 'admin', 'owner')),
  category_id TEXT REFERENCES channel_categories(id) ON DELETE SET NULL,
  position BIGINT NOT NULL DEFAULT 0,
  archived_at TEXT,
  created_by TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (kind <> 'channel' OR (name IS NOT NULL AND visibility IS NOT NULL AND post_role IS NOT NULL))
);

CREATE TABLE conversation_participants (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  conversation_id TEXT NOT NULL REFERENCES conversations(id),
  participant_id TEXT NOT NULL,
  participant_type TEXT NOT NULL CHECK (participant_type IN ('user', 'agent')),
  added_at TEXT NOT NULL,
  PRIMARY KEY (conversation_id, participant_id, participant_type)
);

CREATE TABLE messages (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL REFERENCES conversations(id),
  author_id TEXT NOT NULL,
  author_type TEXT NOT NULL CHECK (author_type IN ('user', 'agent', 'integration')),
  body TEXT NOT NULL,
  reply_to_message_id TEXT REFERENCES messages(id),
  created_at TEXT NOT NULL
, thread_root_id TEXT REFERENCES messages(id) ON DELETE CASCADE);

CREATE TABLE message_mentions (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  message_id TEXT NOT NULL REFERENCES messages(id),
  target_id TEXT NOT NULL,
  target_type TEXT NOT NULL CHECK (target_type IN ('user', 'agent')),
  PRIMARY KEY (message_id, target_id, target_type)
);

CREATE TABLE devices (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  owner_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  public_key TEXT NOT NULL UNIQUE,
  platform TEXT,
  capabilities TEXT NOT NULL DEFAULT '{}',
  last_seen_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE runtime_bindings (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  agent_id TEXT NOT NULL REFERENCES agents(id),
  runtime_kind TEXT NOT NULL CHECK (runtime_kind IN ('native', 'claude-code', 'codex', 'gemini-cli')),
  workspace_path TEXT NOT NULL,
  vendor_state TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
, device_id TEXT REFERENCES devices(id) ON DELETE SET NULL, workspace_id TEXT, options TEXT NOT NULL DEFAULT '{}');

CREATE TABLE runtime_sessions (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  agent_id TEXT NOT NULL REFERENCES agents(id),
  conversation_id TEXT NOT NULL REFERENCES conversations(id),
  runtime_binding_id TEXT NOT NULL REFERENCES runtime_bindings(id),
  status TEXT NOT NULL CHECK (status IN ('idle', 'running', 'waiting_approval', 'error', 'closed')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE agent_runs (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  run_id TEXT PRIMARY KEY,
  root_run_id TEXT NOT NULL,
  causation_id TEXT,
  hop_count BIGINT NOT NULL CHECK (hop_count >= 0 AND hop_count <= 4),
  agent_id TEXT NOT NULL REFERENCES agents(id),
  conversation_id TEXT NOT NULL REFERENCES conversations(id),
  created_at TEXT NOT NULL
, status TEXT NOT NULL DEFAULT 'completed'
  CHECK (status IN ('queued', 'running', 'completed', 'failed', 'cancelled')), trigger TEXT NOT NULL DEFAULT 'message', trigger_message_id TEXT, result_message_id TEXT, started_at TEXT, finished_at TEXT, error_code TEXT, error_message TEXT);

CREATE TABLE approvals (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(run_id),
  agent_id TEXT NOT NULL REFERENCES agents(id),
  action TEXT NOT NULL,
  details TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'denied', 'expired')),
  created_at TEXT NOT NULL,
  resolved_at TEXT
, capability TEXT, action_hash TEXT, expires_at TEXT);

CREATE TABLE provider_configs (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('anthropic', 'openai', 'openrouter', 'deepseek', 'openai-compatible', 'claude-subscription', 'ollama')),
  api_key TEXT,
  base_url TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE jobs (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  payload TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'done', 'failed')) DEFAULT 'pending',
  attempts BIGINT NOT NULL DEFAULT 0,
  last_error TEXT,
  dedupe_key TEXT,
  run_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE memory_facts (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  agent_id TEXT NOT NULL REFERENCES agents(id),
  content TEXT NOT NULL,
  content_key TEXT NOT NULL,
  source TEXT NOT NULL CHECK (source IN ('conversation', 'manual', 'summary')),
  tags TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE conversation_summaries (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  conversation_id TEXT PRIMARY KEY REFERENCES conversations(id),
  summary TEXT NOT NULL,
  up_to_message_id TEXT NOT NULL REFERENCES messages(id),
  updated_at TEXT NOT NULL
);

CREATE TABLE provider_oauth_states (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  state TEXT PRIMARY KEY,
  provider_kind TEXT NOT NULL,
  provider_id TEXT NOT NULL,
  code_verifier TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);

CREATE TABLE device_pairings (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  poll_token_hash TEXT NOT NULL,
  user_code TEXT NOT NULL UNIQUE,
  device_id TEXT NOT NULL,
  device_name TEXT NOT NULL,
  public_key TEXT NOT NULL,
  platform TEXT,
  expires_at TEXT NOT NULL,
  approved_by TEXT REFERENCES users(id) ON DELETE CASCADE,
  approved_at TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE external_identities (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  provider TEXT NOT NULL,
  subject TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY (provider, subject)
);

CREATE TABLE handoff_nonces (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  nonce TEXT PRIMARY KEY,
  expires_at TEXT NOT NULL
);

CREATE TABLE invites (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  code_hash TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL CHECK (role IN ('admin', 'member')),
  created_by TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  used_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  -- A note for whoever reads the list later: "the new designer", "CI".
  label TEXT
, email TEXT, revoked_at TEXT);

CREATE TABLE provider_calls (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  provider_id TEXT NOT NULL,
  provider_kind TEXT NOT NULL,
  model TEXT NOT NULL,
  -- What the call was for: 'agent_turn' today, room for 'routing', 'summary'.
  purpose TEXT NOT NULL,
  agent_id TEXT,
  run_id TEXT,
  root_run_id TEXT,
  conversation_id TEXT,
  -- 1 for the first try; retries count up from there.
  attempt BIGINT NOT NULL,
  -- 1 when this call went to the agent's fallback provider/model.
  fallback BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK (status IN ('ok', 'error')),
  error_code TEXT,
  input_tokens BIGINT NOT NULL DEFAULT 0,
  output_tokens BIGINT NOT NULL DEFAULT 0,
  -- Estimated cost in millionths of a US dollar; NULL when the model has no price.
  cost_micros BIGINT,
  latency_ms BIGINT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE model_prices (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  provider_kind TEXT NOT NULL,
  model TEXT NOT NULL,
  input_per_mtok_micros BIGINT NOT NULL CHECK (input_per_mtok_micros >= 0),
  output_per_mtok_micros BIGINT NOT NULL CHECK (output_per_mtok_micros >= 0),
  updated_at TEXT NOT NULL,
  PRIMARY KEY (provider_kind, model)
);

CREATE TABLE budgets (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  scope TEXT NOT NULL CHECK (scope IN ('server', 'agent')),
  agent_id TEXT REFERENCES agents(id) ON DELETE CASCADE,
  period TEXT NOT NULL CHECK (period IN ('daily', 'monthly')),
  limit_micros BIGINT NOT NULL CHECK (limit_micros > 0),
  -- What happens at the limit: tell people, stop the agent, or move it to
  -- its fallback model.
  action TEXT NOT NULL CHECK (action IN ('warn', 'block', 'fallback')),
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK ((scope = 'server') = (agent_id IS NULL))
);

CREATE TABLE budget_alerts (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  budget_id TEXT NOT NULL REFERENCES budgets(id) ON DELETE CASCADE,
  period_start TEXT NOT NULL,
  threshold BIGINT NOT NULL,
  spent_micros BIGINT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (budget_id, period_start, threshold)
);

CREATE TABLE run_events (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  run_id TEXT NOT NULL REFERENCES agent_runs(run_id) ON DELETE CASCADE,
  seq BIGINT NOT NULL,
  type TEXT NOT NULL,
  data TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (run_id, seq)
);

CREATE TABLE agent_delegates (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  delegate_agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY (agent_id, delegate_agent_id),
  CHECK (agent_id <> delegate_agent_id)
);

CREATE TABLE secrets (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
    CHECK (length(name) <= 64 AND name ~ '^[A-Z][A-Z0-9_]*$'),
  description TEXT NOT NULL DEFAULT '',
  -- NULL once revoked: the value is gone, the record of it is not.
  ciphertext TEXT,
  version BIGINT NOT NULL DEFAULT 1,
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  rotated_at TEXT,
  revoked_at TEXT
);

CREATE TABLE secret_grants (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  secret_id TEXT NOT NULL REFERENCES secrets(id) ON DELETE CASCADE,
  grantee_type TEXT NOT NULL
    CHECK (grantee_type IN ('agent', 'runtime', 'mcp_server', 'automation', 'integration', 'skill')),
  grantee_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (secret_id, grantee_type, grantee_id)
);

CREATE TABLE secret_audit (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  secret_id TEXT NOT NULL,
  secret_name TEXT NOT NULL,
  action TEXT NOT NULL,
  actor_type TEXT NOT NULL CHECK (actor_type IN ('user', 'agent', 'mcp_server', 'skill', 'runtime', 'automation', 'integration', 'system')),
  actor_id TEXT,
  detail TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);

CREATE TABLE mcp_servers (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  transport TEXT NOT NULL CHECK (transport IN ('http', 'stdio')),
  url TEXT,
  command TEXT,
  args TEXT NOT NULL DEFAULT '[]',
  -- Headers and environment are encrypted as a whole: they are where
  -- credentials go when nobody used a {{secret:NAME}} reference.
  headers TEXT NOT NULL,
  env TEXT NOT NULL,
  -- What the server can do that an admin must acknowledge before an agent
  -- gets its tools: 'shell', 'filesystem', 'network'.
  capabilities TEXT NOT NULL DEFAULT '[]',
  enabled BIGINT NOT NULL DEFAULT 1,
  -- What the last successful discovery found, and which of it is switched off.
  tools TEXT NOT NULL DEFAULT '[]',
  disabled_tools TEXT NOT NULL DEFAULT '[]',
  last_tested_at TEXT,
  last_error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK ((transport = 'http') = (url IS NOT NULL)),
  CHECK ((transport = 'stdio') = (command IS NOT NULL))
);

CREATE TABLE agent_mcp_tools (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  server_id TEXT NOT NULL REFERENCES mcp_servers(id) ON DELETE CASCADE,
  tool_name TEXT NOT NULL,
  -- The capabilities acknowledged when this tool was given to the agent.
  granted_capabilities TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL,
  PRIMARY KEY (agent_id, server_id, tool_name)
);

CREATE TABLE skills (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE CHECK (length(slug) <= 64 AND slug ~ '^[a-z0-9][a-z0-9-]*$'),
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  instructions TEXT NOT NULL,
  -- The settings an assignment fills in: [{key, label, secret, required}].
  config_fields TEXT NOT NULL DEFAULT '[]',
  -- Where it came from: written here ('custom') or installed from a manifest
  -- ('installed'), with the origin kept for a future registry to update from.
  source TEXT NOT NULL CHECK (source IN ('custom', 'installed')),
  source_ref TEXT,
  version TEXT NOT NULL DEFAULT '1',
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE agent_skills (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
  -- Values for the skill's fields. A secret field holds a {{secret:NAME}}
  -- reference, never a value.
  config TEXT NOT NULL DEFAULT '{}',
  enabled BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (agent_id, skill_id)
);

CREATE TABLE crewly_connection (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id BIGINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  cloud_url TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'connected', 'revoked')),
  device_code_ciphertext TEXT,
  user_code TEXT,
  verification_url TEXT,
  link_expires_at TEXT,
  poll_interval BIGINT,
  instance_id TEXT,
  credential_ciphertext TEXT,
  credential_version BIGINT,
  scopes TEXT NOT NULL DEFAULT '[]',
  connected_at TEXT,
  last_checked_at TEXT,
  updated_at TEXT NOT NULL
, inbound_domain TEXT, inbound_key TEXT);

CREATE TABLE crewly_connection_audit (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  action TEXT NOT NULL,
  actor_type TEXT NOT NULL CHECK (actor_type IN ('user', 'system')),
  actor_id TEXT,
  detail TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);

CREATE TABLE mail_settings (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id BIGINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  provider TEXT NOT NULL CHECK (provider IN ('disabled', 'crewly', 'smtp', 'resend', 'postmark')),
  from_address TEXT,
  config TEXT NOT NULL DEFAULT '{}',
  secret_ciphertext TEXT,
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE mail_deliveries (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  idempotency_key TEXT UNIQUE,
  category TEXT NOT NULL,
  recipient TEXT NOT NULL,
  subject TEXT NOT NULL,
  payload_ciphertext TEXT,
  provider TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('queued', 'sent', 'retrying', 'failed')),
  attempts BIGINT NOT NULL DEFAULT 0,
  error_class TEXT,
  last_error TEXT,
  provider_message_id TEXT,
  next_attempt_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  sent_at TEXT
);

CREATE TABLE mail_reply_tokens (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  token TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL
);

CREATE TABLE mail_inbound_routes (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  address TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  posted_by TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL
);

CREATE TABLE mail_inbound (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('reply', 'route')),
  sender TEXT NOT NULL,
  recipient TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('delivered', 'rejected')),
  reason TEXT,
  conversation_id TEXT,
  message_id TEXT,
  received_at TEXT NOT NULL,
  processed_at TEXT NOT NULL
);

CREATE TABLE notifications (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  url TEXT,
  conversation_id TEXT,
  created_at TEXT NOT NULL,
  read_at TEXT
);

CREATE TABLE notification_preferences (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  channel TEXT NOT NULL CHECK (channel IN ('in_app', 'email')),
  mode TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (user_id, event_type, channel)
);

CREATE TABLE notification_deliveries (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  dedupe_key TEXT NOT NULL,
  recipient TEXT NOT NULL,
  channel TEXT NOT NULL CHECK (channel IN ('in_app', 'email')),
  collapse_key TEXT,
  status TEXT NOT NULL CHECK (status IN ('pending', 'delivered', 'failed', 'skipped')),
  reason TEXT,
  attempts BIGINT NOT NULL DEFAULT 0,
  last_error TEXT,
  mail_delivery_id TEXT,
  payload_ciphertext TEXT,
  next_attempt_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (dedupe_key, recipient, channel)
);

CREATE TABLE notification_digest_settings (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  frequency TEXT NOT NULL CHECK (frequency IN ('daily', 'weekly')),
  hour_utc BIGINT NOT NULL CHECK (hour_utc BETWEEN 0 AND 23),
  weekday BIGINT CHECK (weekday BETWEEN 0 AND 6),
  updated_at TEXT NOT NULL
);

CREATE TABLE notification_digests (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  period_end TEXT NOT NULL,
  item_count BIGINT NOT NULL,
  mail_delivery_id TEXT,
  created_at TEXT NOT NULL,
  UNIQUE (user_id, period_end)
);

CREATE TABLE channel_agent_blocks (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  agent_id TEXT NOT NULL,
  blocked_by TEXT,
  created_at TEXT NOT NULL,
  PRIMARY KEY (conversation_id, agent_id)
);

CREATE TABLE agent_conversation_routing (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  mode TEXT NOT NULL CHECK (mode IN ('always', 'mention_only', 'relevant', 'disabled')),
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (agent_id, conversation_id)
);

CREATE TABLE connectors (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  provider TEXT NOT NULL,
  account_id TEXT,
  account_name TEXT,
  account_url TEXT,
  scopes TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL CHECK (status IN ('pending', 'connected', 'action_required', 'permission_revoked', 'rate_limited', 'provider_unavailable', 'revoked')),
  owner_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_type TEXT,
  credential_ciphertext TEXT,
  metadata TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  last_used_at TEXT,
  last_checked_at TEXT,
  revoked_at TEXT,
  last_error TEXT
);

CREATE TABLE connector_oauth_states (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  state TEXT PRIMARY KEY,
  connector_id TEXT NOT NULL REFERENCES connectors(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  code_verifier TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  callback_url TEXT NOT NULL,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);

CREATE TABLE connector_grants (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  connector_id TEXT NOT NULL REFERENCES connectors(id) ON DELETE CASCADE,
  grantee_type TEXT NOT NULL CHECK (grantee_type IN ('agent', 'automation', 'integration')),
  grantee_id TEXT NOT NULL,
  capability TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (connector_id, grantee_type, grantee_id, capability)
);

CREATE TABLE connector_audit (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  connector_id TEXT,
  provider TEXT NOT NULL,
  action TEXT NOT NULL,
  actor_type TEXT NOT NULL CHECK (actor_type IN ('user', 'agent', 'automation', 'integration', 'system')),
  actor_id TEXT,
  detail TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);

CREATE TABLE incoming_webhooks (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  channel_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  created_by TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  last_used_at TEXT,
  revoked_at TEXT
);

CREATE TABLE incoming_webhook_events (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  webhook_id TEXT NOT NULL REFERENCES incoming_webhooks(id) ON DELETE CASCADE,
  external_event_id TEXT NOT NULL,
  message_id TEXT,
  created_at TEXT NOT NULL,
  PRIMARY KEY (webhook_id, external_event_id)
);

CREATE TABLE server_branding (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id BIGINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  display_name TEXT NOT NULL DEFAULT 'Crewly',
  tagline TEXT NOT NULL DEFAULT '',
  icon_data_url TEXT,
  updated_at TEXT NOT NULL
);

CREATE TABLE attachments (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  message_id TEXT REFERENCES messages(id) ON DELETE SET NULL,
  uploaded_by TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  filename TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
  storage_key TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL
);

CREATE TABLE artifacts (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  attachment_id TEXT PRIMARY KEY REFERENCES attachments(id) ON DELETE CASCADE,
  run_id TEXT NOT NULL REFERENCES agent_runs(run_id) ON DELETE CASCADE,
  agent_id TEXT NOT NULL REFERENCES agents(id),
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL
);

CREATE TABLE server_roles (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  permissions TEXT NOT NULL DEFAULT '[]',
  built_in BIGINT NOT NULL DEFAULT 0 CHECK (built_in IN (0, 1)),
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE user_server_roles (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id TEXT NOT NULL REFERENCES server_roles(id) ON DELETE CASCADE,
  assigned_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE automations (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
  trigger_type TEXT NOT NULL CHECK (trigger_type IN ('webhook', 'message', 'schedule', 'run')),
  trigger_config TEXT NOT NULL DEFAULT '{}',
  conditions TEXT NOT NULL DEFAULT '{}',
  actions TEXT NOT NULL DEFAULT '[]',
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE automation_runs (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  automation_id TEXT NOT NULL REFERENCES automations(id) ON DELETE CASCADE,
  trigger_event_id TEXT,
  dedupe_key TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'failed', 'skipped')),
  hop_count BIGINT NOT NULL DEFAULT 0,
  input TEXT NOT NULL DEFAULT '{}',
  output TEXT NOT NULL DEFAULT '{}',
  error TEXT,
  created_at TEXT NOT NULL,
  finished_at TEXT,
  UNIQUE (automation_id, dedupe_key)
);

CREATE TABLE capability_policies (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  agent_id TEXT REFERENCES agents(id) ON DELETE CASCADE,
  capability TEXT NOT NULL,
  decision TEXT NOT NULL CHECK (decision IN ('allow', 'ask', 'deny')),
  scope TEXT NOT NULL DEFAULT '{}',
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE auth_settings (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id BIGINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  mode TEXT NOT NULL DEFAULT 'local' CHECK (mode IN ('local', 'crewly', 'both')),
  crewly_enabled BIGINT NOT NULL DEFAULT 0 CHECK (crewly_enabled IN (0, 1)),
  handoff_public_key TEXT,
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE crewly_identity_states (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  state TEXT PRIMARY KEY,
  nonce TEXT NOT NULL,
  code_verifier TEXT NOT NULL,
  redirect_uri TEXT NOT NULL,
  invite_token TEXT,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);

CREATE TABLE slack_imports (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  connector_id TEXT NOT NULL REFERENCES connectors(id) ON DELETE CASCADE,
  requested_by TEXT NOT NULL REFERENCES users(id),
  status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'completed_with_errors', 'failed')),
  options TEXT NOT NULL DEFAULT '{}',
  summary TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE slack_import_mappings (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  connector_id TEXT NOT NULL REFERENCES connectors(id) ON DELETE CASCADE,
  remote_type TEXT NOT NULL CHECK (remote_type IN ('channel', 'message', 'member')),
  remote_id TEXT NOT NULL,
  local_id TEXT,
  outcome TEXT NOT NULL CHECK (outcome IN ('created', 'matched', 'skipped', 'failed')),
  detail TEXT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (connector_id, remote_type, remote_id)
);

CREATE TABLE federation_settings (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id BIGINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  server_id TEXT NOT NULL,
  enabled BIGINT NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
  display_name TEXT NOT NULL DEFAULT 'Crewly server',
  updated_at TEXT NOT NULL
);

CREATE TABLE federation_connections (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  remote_url TEXT NOT NULL,
  remote_server_id TEXT,
  remote_connection_id TEXT,
  remote_name TEXT,
  status TEXT NOT NULL CHECK (status IN ('pending', 'active', 'revoked', 'unreachable', 'incompatible')),
  scopes TEXT NOT NULL DEFAULT '[]',
  local_secret_ciphertext TEXT,
  remote_secret_ciphertext TEXT,
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  revoked_at TEXT,
  last_seen_at TEXT,
  last_error TEXT
);

CREATE TABLE federation_events (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  connection_id TEXT REFERENCES federation_connections(id) ON DELETE SET NULL,
  origin_server_id TEXT NOT NULL,
  causation_id TEXT,
  event_type TEXT NOT NULL,
  scope TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  hop_count BIGINT NOT NULL DEFAULT 0,
  payload TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL CHECK (status IN ('accepted', 'delivered', 'duplicate', 'rejected', 'failed')),
  created_at TEXT NOT NULL
);

CREATE TABLE browser_sessions (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  run_id TEXT REFERENCES agent_runs(run_id) ON DELETE CASCADE,
  agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('active', 'closed', 'expired', 'failed')),
  persistent BIGINT NOT NULL DEFAULT 0 CHECK (persistent IN (0, 1)),
  page_count BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  closed_at TEXT,
  last_error TEXT
);

CREATE TABLE browser_actions (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES browser_sessions(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  url TEXT,
  status TEXT NOT NULL CHECK (status IN ('ok', 'denied', 'failed')),
  artifact_id TEXT REFERENCES attachments(id) ON DELETE SET NULL,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE TABLE registry_settings (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id BIGINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  enabled BIGINT NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
  registry_url TEXT,
  allow_unverified BIGINT NOT NULL DEFAULT 0 CHECK (allow_unverified IN (0, 1)),
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE registry_installations (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  id TEXT PRIMARY KEY,
  item_type TEXT NOT NULL CHECK (item_type IN ('skill', 'mcp_preset')),
  registry_id TEXT NOT NULL,
  name TEXT NOT NULL,
  publisher TEXT NOT NULL,
  version TEXT NOT NULL,
  pinned_version TEXT,
  verified BIGINT NOT NULL DEFAULT 0 CHECK (verified IN (0, 1)),
  manifest TEXT NOT NULL,
  installed_resource_id TEXT,
  installed_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  installed_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(item_type, registry_id)
);

CREATE TABLE message_threads (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  root_message_id TEXT PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'archived')),
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  resolved_at TEXT,
  archived_at TEXT
);

CREATE TABLE message_thread_reads (
  rowid BIGINT GENERATED ALWAYS AS IDENTITY,
  root_message_id TEXT NOT NULL REFERENCES message_threads(root_message_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  last_read_at TEXT NOT NULL,
  PRIMARY KEY (root_message_id, user_id)
);

CREATE INDEX idx_event_log_topic_seq ON event_log (topic, seq);

CREATE INDEX idx_sessions_user_id ON sessions (user_id);

CREATE INDEX idx_agents_owner ON agents (owner_user_id);

CREATE INDEX idx_conversation_participants_participant
  ON conversation_participants (participant_id, participant_type);

CREATE INDEX idx_runtime_bindings_agent ON runtime_bindings (agent_id);

CREATE INDEX idx_runtime_sessions_agent_conversation ON runtime_sessions (agent_id, conversation_id);

CREATE INDEX idx_agent_runs_root ON agent_runs (root_run_id);

CREATE INDEX idx_approvals_status ON approvals (status);

CREATE INDEX idx_jobs_status_run_at ON jobs (status, run_at);

CREATE UNIQUE INDEX idx_jobs_pending_dedupe ON jobs (dedupe_key) WHERE status = 'pending';

CREATE UNIQUE INDEX idx_memory_facts_agent_content_key ON memory_facts (agent_id, content_key);

CREATE INDEX idx_memory_facts_agent_created ON memory_facts (agent_id, created_at);

CREATE INDEX provider_oauth_states_expiry_idx ON provider_oauth_states(expires_at);

CREATE INDEX devices_owner_idx ON devices(owner_user_id);

CREATE INDEX device_pairings_expiry_idx ON device_pairings(expires_at);

CREATE INDEX external_identities_user_idx ON external_identities (user_id);

CREATE INDEX handoff_nonces_expiry_idx ON handoff_nonces (expires_at);

CREATE INDEX invites_expiry_idx ON invites (expires_at);

CREATE INDEX provider_calls_created_idx ON provider_calls (created_at);

CREATE INDEX provider_calls_provider_idx ON provider_calls (provider_id, created_at);

CREATE INDEX provider_calls_agent_idx ON provider_calls (agent_id, created_at);

CREATE INDEX provider_calls_run_idx ON provider_calls (run_id);

CREATE INDEX provider_calls_root_idx ON provider_calls (root_run_id);

CREATE UNIQUE INDEX budgets_scope_idx ON budgets (scope, COALESCE(agent_id, ''), period);

CREATE INDEX agent_runs_status_idx ON agent_runs (status, created_at);

CREATE INDEX agent_runs_agent_idx ON agent_runs (agent_id, created_at);

CREATE INDEX agent_runs_result_message_idx ON agent_runs (result_message_id);

CREATE INDEX secret_grants_grantee_idx ON secret_grants (grantee_type, grantee_id);

CREATE INDEX secret_audit_secret_idx ON secret_audit (secret_id, created_at);

CREATE INDEX secret_audit_created_idx ON secret_audit (created_at);

CREATE INDEX crewly_connection_audit_created_idx ON crewly_connection_audit (created_at);

CREATE INDEX mail_deliveries_due_idx ON mail_deliveries (status, next_attempt_at);

CREATE INDEX mail_deliveries_created_idx ON mail_deliveries (created_at);

CREATE UNIQUE INDEX mail_reply_tokens_pair_idx ON mail_reply_tokens (conversation_id, user_id);

CREATE INDEX mail_inbound_processed_idx ON mail_inbound (processed_at);

CREATE INDEX notifications_user_idx ON notifications (user_id, created_at);

CREATE INDEX notification_deliveries_collapse_idx ON notification_deliveries (recipient, channel, event_type, collapse_key, created_at);

CREATE INDEX notification_deliveries_due_idx ON notification_deliveries (status, next_attempt_at);

CREATE INDEX idx_conversations_channels ON conversations (kind, category_id, position);

CREATE INDEX idx_agent_conversation_routing_conversation
  ON agent_conversation_routing (conversation_id);

CREATE INDEX invites_email_idx ON invites (email);

CREATE UNIQUE INDEX connectors_provider_account_idx ON connectors(provider, account_id) WHERE account_id IS NOT NULL AND status <> 'revoked';

CREATE INDEX connectors_owner_idx ON connectors(owner_user_id, created_at);

CREATE INDEX connector_oauth_states_expiry_idx ON connector_oauth_states(expires_at);

CREATE INDEX connector_grants_grantee_idx ON connector_grants(grantee_type, grantee_id);

CREATE INDEX connector_audit_connector_idx ON connector_audit(connector_id, created_at);

CREATE INDEX connector_audit_created_idx ON connector_audit(created_at);

CREATE INDEX incoming_webhooks_channel_idx ON incoming_webhooks(channel_id, created_at);

CREATE INDEX idx_messages_conversation_created ON messages(conversation_id, created_at);

CREATE INDEX attachments_message_idx ON attachments(message_id, created_at);

CREATE INDEX attachments_conversation_idx ON attachments(conversation_id, created_at);

CREATE INDEX artifacts_run_idx ON artifacts(run_id, created_at);

CREATE INDEX artifacts_conversation_idx ON artifacts(conversation_id, created_at);

CREATE INDEX user_server_roles_role_idx ON user_server_roles(role_id, created_at);

CREATE INDEX automations_enabled_trigger_idx ON automations(enabled, trigger_type);

CREATE INDEX automation_runs_created_idx ON automation_runs(automation_id, created_at);

CREATE INDEX capability_policies_agent_idx ON capability_policies(agent_id, capability);

CREATE UNIQUE INDEX approvals_pending_action_idx ON approvals(run_id, action_hash)
  WHERE status = 'pending' AND action_hash IS NOT NULL;

CREATE UNIQUE INDEX federation_remote_idx ON federation_connections(remote_url) WHERE status <> 'revoked';

CREATE INDEX federation_events_connection_idx ON federation_events(connection_id, created_at);

CREATE INDEX browser_actions_session_idx ON browser_actions(session_id, created_at);

CREATE INDEX messages_thread_idx ON messages(thread_root_id, created_at);

-- Rows the SQLite migrations seed, which a fresh server depends on.

-- From 0039_server_branding.sql.
INSERT INTO server_branding (id, updated_at)
  VALUES (1, '1970-01-01T00:00:00.000Z');

-- From 0042_server_roles.sql.
INSERT INTO server_roles (id, name, description, permissions, built_in, created_at, updated_at) VALUES
  ('builtin-owner', 'Owner', 'Full server authority and recovery control.', '["members.view","members.manage","members.invite","agents.create","agents.manage","providers.manage","integrations.manage","automations.manage","server.settings","operations.view","roles.manage"]', 1, '1970-01-01T00:00:00.000Z', '1970-01-01T00:00:00.000Z'),
  ('builtin-admin', 'Admin', 'Day-to-day server administration without ownership transfer.', '["members.view","members.manage","members.invite","agents.create","agents.manage","providers.manage","integrations.manage","automations.manage","server.settings","operations.view","roles.manage"]', 1, '1970-01-01T00:00:00.000Z', '1970-01-01T00:00:00.000Z'),
  ('builtin-member', 'Member', 'Normal workspace participation.', '["agents.create"]', 1, '1970-01-01T00:00:00.000Z', '1970-01-01T00:00:00.000Z');

-- From 0044_collaboration_platform.sql.
INSERT INTO auth_settings (id, mode, crewly_enabled, updated_at)
VALUES (1, 'local', 0, '1970-01-01T00:00:00.000Z');

-- From 0044_collaboration_platform.sql.
INSERT INTO registry_settings (id, enabled, allow_unverified, updated_at)
VALUES (1, 0, 0, '1970-01-01T00:00:00.000Z');

-- Emails are compared case-insensitively (SQLite: COLLATE NOCASE).
CREATE INDEX users_email_lower_idx ON users (lower(email));
